<#
.SYNOPSIS
    Detects silent drift between environment roots that are supposed to be
    byte-identical copies of each other (finding R10, option (b) — see
    docs/reviews/2026-07-terraform-and-docs-review.md §2.2).

.DESCRIPTION
    This platform's reuse-by-verbatim-copy doctrine (E7) treats
    `environments/dev/` and `environments/staging/` as the SAME code,
    hand-copied on purpose instead of factored into a module (that
    refactor is the longer-term R10 option (a); this script is the
    "one script" interim from option (b)). The review verified that,
    as of 2026-07-11, all 11 shared *.tf files are byte-identical across
    dev and staging, and the two `.terraform.lock.hcl` files match too.

    Nothing currently enforces that. The first dev-only hotfix that isn't
    re-copied to staging silently forks the platform, and every fix already
    tracked as debt in one environment (T2, T12, R5, …) gets doubled instead
    of fixed once. This script makes that failure mode loud instead of
    silent: it fails CI (exit 1) the moment any *.tf file diverges between
    environment roots, with a report of exactly which file and which lines.

    What is compared:
      - Every `*.tf` file present in each environment root, EXCEPT the files
        in $ExcludePatterns below (things that are SUPPOSED to differ per
        environment). Comparison is against the first environment in
        -Environments (the "reference" env); every other environment is
        diffed against it.
      - Presence: a `*.tf` file that exists in one environment's root but
        not another is reported as a failure too (that is drift — a file
        that was added/removed in only one copy).
      - `.terraform.lock.hcl`: compared the same way, but reported as a
        WARNING, not a failure (see "Why the lock file is warning-only"
        below).

    What is intentionally excluded ($ExcludePatterns) because it is
    per-environment truth, not copied code:
      - backend.tf                  — different storage account / state key
                                       per environment (E1: partial backend
                                       config; never hardcoded).
      - terraform.tfvars            — per-environment values (committed by
                                       policy; content differs by design).
      - terraform.tfvars.example    — same, for the placeholder template.
      - backend.hcl.example         — per-environment placeholder backend
                                       config (gitignored `backend.hcl` is
                                       generated from this).
      - *.example                   — catch-all for any other per-env
                                       example/template file.

    Why the lock file is warning-only, not a failure:
      `.terraform.lock.hcl` is machine-generated by `terraform init` /
      `terraform providers lock`, not hand-copied like the *.tf files. A
      difference there is a useful signal (dependency versions should track
      together — the review confirmed dev and staging pin identical azurerm
      /databricks/azuread/azapi versions) but it can legitimately differ for
      operational reasons that are NOT a human silently forking the
      platform — e.g. someone ran `terraform providers lock
      -platform=<extra>` in only one environment to add a CI runner
      platform's hashes, or re-ran `init -upgrade` in one environment ahead
      of the other during a rollout window. Treat a lock-file warning as
      "go investigate," not "the build is broken."

    Line-ending handling:
      This repo is authored on Windows (CRLF-by-default tooling) and CI runs
      on ubuntu-latest (LF). A file that is byte-identical in content but
      saved with different line endings on different platforms is NOT
      drift. Every comparison in this script first normalizes both CRLF
      (`` `r`n ``) and lone CR (`` `r ``) to LF (`` `n ``) before comparing,
      so only real content differences are reported.

.PARAMETER Environments
    Ordered list of environment names (directory names under
    `environments/`) to compare. The FIRST entry is the reference; every
    other entry is diffed against it. Default: @('dev', 'staging') — the
    two environments the review scoped and verified. Add 'prod' here once
    prod is a real (non-stub) copy instead of the current placeholder.

.PARAMETER EnvironmentsPath
    Path to the `environments/` directory. Defaults to `../environments`
    relative to this script (i.e. `terraform/azure/databricks/environments`
    when the script lives in `terraform/azure/databricks/scripts/`).

.PARAMETER ExcludePatterns
    Wildcard filename patterns (matched with `-like`) that are allowed to
    differ across environments and are skipped entirely. Defaults to the
    per-environment files documented above. Pass your own list to override.

.PARAMETER Quiet
    Suppress the per-file "match" lines on a clean run. Divergence reports
    (failures and warnings) are ALWAYS printed in full, regardless of
    -Quiet — this switch only quiets the success path.

.EXAMPLE
    ./scripts/check-env-drift.ps1

.EXAMPLE
    # Once prod stops being a 0-byte stub:
    ./scripts/check-env-drift.ps1 -Environments dev,staging,prod

.EXAMPLE
    ./scripts/check-env-drift.ps1 -Quiet
#>

[CmdletBinding()]
param(
    [string[]]$Environments = @('dev', 'staging'),

    [string]$EnvironmentsPath = (Join-Path $PSScriptRoot '..' 'environments'),

    [string[]]$ExcludePatterns = @(
        'backend.tf',
        'terraform.tfvars',
        'terraform.tfvars.example',
        'backend.hcl.example',
        '*.example'
    ),

    [switch]$Quiet
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Write-Info($msg) {
    if (-not $Quiet) { Write-Host $msg -ForegroundColor Cyan }
}

function Get-NormalizedContent {
    param([Parameter(Mandatory)][string]$Path)
    # Normalize CRLF and lone CR to LF so cross-platform (Windows author /
    # Linux CI) line-ending differences never register as drift.
    $raw = Get-Content -LiteralPath $Path -Raw -ErrorAction Stop
    if ($null -eq $raw) { return '' }
    return ($raw -replace "`r`n", "`n" -replace "`r", "`n")
}

function Get-LineDiff {
    # Returns a short, readable list of the first differing lines between
    # two already-normalized strings (capped so one wildly different file
    # doesn't flood the report).
    param(
        [Parameter(Mandatory)][string]$NormA,
        [Parameter(Mandatory)][string]$NormB,
        [int]$MaxLines = 20
    )
    $linesA = $NormA -split "`n"
    $linesB = $NormB -split "`n"
    $max = [Math]::Max($linesA.Count, $linesB.Count)
    $out = [System.Collections.Generic.List[string]]::new()
    $shown = 0
    for ($i = 0; $i -lt $max; $i++) {
        $la = if ($i -lt $linesA.Count) { $linesA[$i] } else { '<no line — file is shorter>' }
        $lb = if ($i -lt $linesB.Count) { $linesB[$i] } else { '<no line — file is shorter>' }
        if ($la -ne $lb) {
            if ($shown -ge $MaxLines) {
                $out.Add("      ... more differing lines omitted (capped at $MaxLines) ...")
                break
            }
            $out.Add("    line $($i + 1):")
            $out.Add("      - $la")
            $out.Add("      + $lb")
            $shown++
        }
    }
    return $out
}

function Test-ExcludedFile {
    param([string]$Name, [string[]]$Patterns)
    foreach ($p in $Patterns) {
        if ($Name -like $p) { return $true }
    }
    return $false
}

# --- preflight ---------------------------------------------------------
if ($Environments.Count -lt 2) {
    Write-Error 'Need at least two -Environments to compare.'
    exit 1
}

$EnvironmentsPath = (Resolve-Path -LiteralPath $EnvironmentsPath -ErrorAction Stop).Path
Write-Info "Environment roots directory: $EnvironmentsPath"
Write-Info "Comparing: $($Environments -join ', ') (reference = '$($Environments[0])')"
Write-Info "Excluded filename patterns: $($ExcludePatterns -join ', ')"
Write-Info ''

$envDirs = @{}
foreach ($env in $Environments) {
    $dir = Join-Path $EnvironmentsPath $env
    if (-not (Test-Path -LiteralPath $dir -PathType Container)) {
        Write-Error "Environment root not found: $dir"
        exit 1
    }
    $envDirs[$env] = (Resolve-Path -LiteralPath $dir).Path
}

$referenceEnv = $Environments[0]
$hasFailure = $false
$hasWarning = $false
$report = [System.Collections.Generic.List[string]]::new()

function Compare-FileAcrossEnvs {
    param(
        [string]$FileName,
        [string[]]$EnvList,
        [hashtable]$EnvDirs,
        [string]$ReferenceEnv,
        [ValidateSet('Fail', 'Warn')][string]$Severity
    )

    $refPath = Join-Path $EnvDirs[$ReferenceEnv] $FileName
    $refExists = Test-Path -LiteralPath $refPath -PathType Leaf

    $anyDivergence = $false
    $localReport = [System.Collections.Generic.List[string]]::new()

    foreach ($env in $EnvList) {
        if ($env -eq $ReferenceEnv) { continue }
        $path = Join-Path $EnvDirs[$env] $FileName
        $exists = Test-Path -LiteralPath $path -PathType Leaf

        if ($refExists -and -not $exists) {
            $anyDivergence = $true
            $localReport.Add("  [$Severity] $FileName — exists in '$ReferenceEnv' but is MISSING from '$env'")
            continue
        }
        if (-not $refExists -and $exists) {
            $anyDivergence = $true
            $localReport.Add("  [$Severity] $FileName — exists in '$env' but is MISSING from '$ReferenceEnv'")
            continue
        }
        if (-not $refExists -and -not $exists) {
            continue
        }

        $normRef = Get-NormalizedContent -Path $refPath
        $normOther = Get-NormalizedContent -Path $path

        if ($normRef -ne $normOther) {
            $anyDivergence = $true
            $localReport.Add("  [$Severity] $FileName — '$ReferenceEnv' and '$env' differ:")
            $diffLines = Get-LineDiff -NormA $normRef -NormB $normOther
            foreach ($l in $diffLines) { $localReport.Add($l) }
        }
    }

    return [PSCustomObject]@{
        Diverged = $anyDivergence
        Lines    = $localReport
    }
}

# --- 1. build the union of comparable *.tf files ----------------------
$allTfFiles = [System.Collections.Generic.SortedSet[string]]::new()
foreach ($env in $Environments) {
    Get-ChildItem -LiteralPath $envDirs[$env] -Filter '*.tf' -File |
        Where-Object { -not (Test-ExcludedFile -Name $_.Name -Patterns $ExcludePatterns) } |
        ForEach-Object { [void]$allTfFiles.Add($_.Name) }
}

Write-Info "Comparing $($allTfFiles.Count) *.tf file(s) (post-exclusion) across $($Environments.Count) environments..."
Write-Info ''

foreach ($fileName in $allTfFiles) {
    $result = Compare-FileAcrossEnvs -FileName $fileName -EnvList $Environments -EnvDirs $envDirs `
        -ReferenceEnv $referenceEnv -Severity 'Fail'
    if ($result.Diverged) {
        $hasFailure = $true
        foreach ($l in $result.Lines) { $report.Add($l) }
    }
    else {
        Write-Info "  [ok] $fileName — identical across $($Environments -join ', ')"
    }
}

# --- 2. .terraform.lock.hcl: same mechanism, warning severity ---------
Write-Info ''
Write-Info 'Comparing .terraform.lock.hcl (warning-level; see script header for why)...'
$lockResult = Compare-FileAcrossEnvs -FileName '.terraform.lock.hcl' -EnvList $Environments -EnvDirs $envDirs `
    -ReferenceEnv $referenceEnv -Severity 'Warn'
if ($lockResult.Diverged) {
    $hasWarning = $true
    foreach ($l in $lockResult.Lines) { $report.Add($l) }
}
else {
    Write-Info '  [ok] .terraform.lock.hcl — identical across all environments'
}

# --- 3. report -----------------------------------------------------------
Write-Host ''
if (-not $hasFailure -and -not $hasWarning) {
    Write-Host "PASS: no drift detected across $($Environments -join ', ') ($($allTfFiles.Count) *.tf files + lock file all match)." -ForegroundColor Green
    exit 0
}

if ($hasFailure) {
    Write-Host '================ ENVIRONMENT DRIFT DETECTED ================' -ForegroundColor Red
}
else {
    Write-Host '================ ENVIRONMENT DRIFT WARNINGS ================' -ForegroundColor Yellow
}
foreach ($line in $report) {
    if ($line -match '^\s*\[Fail\]') { Write-Host $line -ForegroundColor Red }
    elseif ($line -match '^\s*\[Warn\]') { Write-Host $line -ForegroundColor Yellow }
    else { Write-Host $line }
}
Write-Host '=============================================================' -ForegroundColor $(if ($hasFailure) { 'Red' } else { 'Yellow' })
Write-Host ''

if ($hasFailure) {
    Write-Host "FAIL: $($Environments -join '/') were supposed to be byte-identical copies (E7 doctrine)." -ForegroundColor Red
    Write-Host "      Re-copy the fix from the intended source of truth to every environment, or if the" -ForegroundColor Red
    Write-Host "      divergence is deliberate, record it (tfvars/backend.tf are the sanctioned places for" -ForegroundColor Red
    Write-Host "      per-environment differences — see -ExcludePatterns) and re-run this check." -ForegroundColor Red
    exit 1
}
else {
    Write-Host 'Lock-file divergence is a warning, not a failure (see script header). Exiting 0.' -ForegroundColor Yellow
    exit 0
}
